
wifi:
  # ssid: !secret wifi_ssid
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  power_save_mode: none
  ap:
    ssid: "UB-Fallback-Hotspot"
    password: "asdfasdf"

api:
  encryption: { key: !secret api_key }

mdns:
  disabled: true

network:
ota:
  platform: esphome

captive_portal:

web_server:
  port: 80
  version: 3

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Strength"
    update_interval: 60s

