
esphome:
  name: under-bed-lighting
  name_add_mac_suffix: True
  friendly_name: "Under Bed Lighting"
  min_version: 2024.6.0

packages:
  base: !include ../packages/base_c3mini.yaml
  wifi: !include ../packages/wifi.yaml

